#!/usr/bin/env node
/**
 * Single source of truth for environment variables.
 *
 * You edit ONE file — the root `.env` — and this script generates the
 * per-package files the toolchains insist on reading from their own dirs:
 *
 *   .env  ──►  frontend/.env.local   (read by Next.js)
 *         ──►  backend/.env          (read by the Firebase Functions CLI)
 *
 * Derived values (defined once in .env, written where needed):
 *   FIREBASE_PROJECT_ID   → NEXT_PUBLIC_FIREBASE_PROJECT_ID (frontend)
 *
 * Run via: pnpm run env:sync   (also runs automatically before `pnpm run dev`)
 */
'use strict'

const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const envPath = path.join(root, '.env')

if (!fs.existsSync(envPath)) {
  console.error(
    '\x1b[31mNo .env file found at the repo root.\x1b[0m\n' +
      'Create it first:  cp .env.example .env  (then fill in your Firebase values)\n' +
      'See docs/ENV-VARS.md for what each variable is.',
  )
  process.exit(1)
}

/** Minimal .env parser — KEY=VALUE lines, # comments, no multiline values. */
function parseEnv(content) {
  const vars = {}
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    let value = trimmed.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    vars[key] = value
  }
  return vars
}

const env = parseEnv(fs.readFileSync(envPath, 'utf8'))
const get = (key) => env[key] ?? ''

const header = (target) =>
  `# GENERATED by scripts/sync-env.js — do not edit this file.\n` +
  `# Edit the root .env instead, then run: pnpm run env:sync\n` +
  `# (${target})\n\n`

// ── frontend/.env.local ──────────────────────────────────────────────
const frontendLines = [header('read by Next.js')]

// All NEXT_PUBLIC_* keys pass through as-is
for (const [key, value] of Object.entries(env)) {
  if (key.startsWith('NEXT_PUBLIC_')) frontendLines.push(`${key}=${value}`)
}
frontendLines.push(`NEXT_PUBLIC_FIREBASE_PROJECT_ID=${get('FIREBASE_PROJECT_ID')}`)
frontendLines.push(`FIREBASE_SERVICE_ACCOUNT_KEY_BASE64=${get('FIREBASE_SERVICE_ACCOUNT_KEY_BASE64')}`)

// ── backend/.env ─────────────────────────────────────────────────────
const backendLines = [
  header('read by the Firebase Functions CLI'),
  `FIREBASE_PROJECT_ID=${get('FIREBASE_PROJECT_ID')}`,
  `FIREBASE_SERVICE_ACCOUNT_KEY_BASE64=${get('FIREBASE_SERVICE_ACCOUNT_KEY_BASE64')}`,
  `CORS_ORIGIN=${get('CORS_ORIGIN')}`,
  `PORT=${get('PORT')}`,
]

fs.writeFileSync(path.join(root, 'frontend', '.env.local'), frontendLines.join('\n') + '\n')
fs.writeFileSync(path.join(root, 'backend', '.env'), backendLines.join('\n') + '\n')

console.log('env:sync  .env → frontend/.env.local, backend/.env')

// Friendly warnings for the values that break the app when missing
const required = ['FIREBASE_PROJECT_ID', 'NEXT_PUBLIC_FIREBASE_API_KEY', 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN']
const missing = required.filter((key) => !get(key))
if (missing.length > 0) {
  console.warn(
    `\x1b[33mWarning: ${missing.join(', ')} ${missing.length === 1 ? 'is' : 'are'} empty in .env — ` +
      `the app will fail at runtime until filled in (see docs/ENV-VARS.md).\x1b[0m`,
  )
}
